#!/bin/bash

# Theme System Development Environment Setup
# Generated by Planner Agent for Task 004

set -e

echo "========================================"
echo "Theme System Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}Project: OpenCode Group Discuss - Theme System${NC}"
echo ""

# Check Node.js version
echo "Checking Node.js version..."
NODE_VERSION=$(node -v | cut -d'v' -f2 | cut -d'.' -f1)
if [ "$NODE_VERSION" -lt 20 ]; then
    echo -e "${RED}Error: Node.js >= 20.0.0 required${NC}"
    echo "Current version: $(node -v)"
    exit 1
fi
echo -e "${GREEN}✓ Node.js $(node -v)${NC}"

# Install dependencies if needed
if [ ! -d "node_modules" ]; then
    echo ""
    echo "Installing dependencies..."
    npm install
    echo -e "${GREEN}✓ Dependencies installed${NC}"
else
    echo -e "${GREEN}✓ Dependencies already installed${NC}"
fi

# Build project
echo ""
echo "Building project..."
npm run build
if [ $? -eq 0 ]; then
    echo -e "${GREEN}✓ Build successful${NC}"
else
    echo -e "${RED}✗ Build failed${NC}"
    exit 1
fi

# Run tests
echo ""
echo "Running tests..."
npm test
if [ $? -eq 0 ]; then
    echo -e "${GREEN}✓ Tests pass${NC}"
else
    echo -e "${YELLOW}⚠ Some tests failed (expected during development)${NC}"
fi

# ============================================
# DEVELOPMENT SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Available Commands:"
echo "  npm run dev     - Watch mode for development"
echo "  npm run build   - Build the project"
echo "  npm test        - Run tests"
echo ""
echo "Theme System Files:"
echo "  src/config/theme.ts         - Theme type definitions"
echo "  src/config/schema.ts        - Configuration schema (will be modified)"
echo "  src/config/ConfigLoader.ts  - Config loader (will be modified)"
echo "  src/tui/ThemeManager.ts     - Theme manager utility"
echo "  src/tui/TranscriptViewer.ts - TUI viewer (will be modified)"
echo ""
echo "Configuration:"
echo "  .opencode/group-discuss.json - Project-level config"
echo "  ~/.config/opencode/group-discuss.json - Global config"
echo ""
echo -e "${BLUE}Next Steps:${NC}"
echo "  1. Implement theme types in src/config/theme.ts"
echo "  2. Add theme config to schema.ts"
echo "  3. Update ConfigLoader to load themes"
echo "  4. Create ThemeManager utility"
echo "  5. Refactor TranscriptViewer to use themes"
echo ""
